title: H3VR Modding Wiki
description: A test.
theme: just-the-docs

url: https://potatoes1286.github.io/testwiki

aux_links:
  Contribute on GitHub: https://github.com/potatoes1286/testwiki


callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


favicon_ico: "/docs/images/Smol_SpannerDog.ico"